project:
  type: website
  render:
    - index.qmd
    - registration.qmd
    - call_for_presentations.qmd
    - author_guidelines.qmd
  output-dir: _site


website:
  site-url: https://www.research-software-africa.org
  title: "RSAfrica26"
  navbar:
    background: "#7C004C"
    foreground: "#FFFFFF"
    left:
      - text: "Home"
        href: index.qmd
      - text: "Call for presentations"
        href: call_for_presentations.qmd
     right:
      - icon: github
        href: https://github.com/Research-Software-Africa/research-software-africa-org
    right:
      - icon: LinkedIn
        href: https://www.linkedin.com/company/rsafrica

  page-footer:
    background: "#7C004C"
    foreground: "#FFFFFF"
    center: "Research Software Africa (RSAfrica26)"

format:
  html:
    theme:
      - cosmo
      - custom.scss
    toc: false
    page-layout: full
